// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

let fibPattern = fun (u,v) -> Some(u,(u+v,u))
let fib = Seq.unfold fibPattern (1,1)
Seq.take 10 (Seq.filter (fun x -> x%2=0) fib) |> Seq.toList |> List.sum