// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

let fibPattern n = Seq.unfold (fun (u,v) -> if u < n then Some(u,(u+v,u)) else None) (1,1)
let fibListSum n = fibPattern n |> Seq.filter (fun x -> x%2=0) |> Seq.toList |> List.sum

fibListSum 4000000 //val it : int = 4613732